name: deep_q
channels:
- defaults
dependencies:
- python=2.7
- pip:
    - rospkg
    - rosdep
    - rosinstall
    - vcstools
    - keras==1.2.1
    - theano
    - pydot==1.1.0
    - numpy
    - scipy
    - scikit-learn
    - pillow
    - h5py
